
	import type { Metadata } from "next";
	import { Geist, Geist_Mono } from "next/font/google";
	import "./globals.css";
	import { Providers } from "@/providers/provider";
	import Header from "@/components/UI/header";


	const geistSans = Geist({
		variable: "--font-geist-sans",
		subsets: ["latin"],
	});

	const geistMono = Geist_Mono({
		variable: "--font-geist-mono",
		subsets: ["latin"],
	});

	export const metadata: Metadata = {
		title: "Северяночка",
		description: "Generated by create next app",
	};

	export default function RootLayout({
		children,
	}: Readonly<{
		children: React.ReactNode;
	}>) {
		return (
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Providers>
						{/* Full-width white background to avoid dark sidebars on wide screens */}
						<div className="w-full bg-white min-h-screen">
							<Header />
							{children}
						</div>
					</Providers>
				</body>
			</html>
		);
	}
