import type { Metadata } from "next";
import { Montserrat, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from 'react-hot-toast';


const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin", "cyrillic"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
});

const rubik = Rubik({
	variable: "--font-rubik",
	subsets: ["latin", "cyrillic"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Северяночка",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} ${geistMono.variable} ${rubik.variable} antialiased`}
			>
				<Providers>
					<div className="w-full bg-white min-h-screen flex flex-col">
						<Header />
						<main className="flex-1">{children}</main>
						<Footer />
					</div>
				</Providers>
				<Toaster />
			</body>
		</html>
	);
}
